<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="cugo_v3">

  <xacro:include filename="$(find cugo_ros2_control)/models/cugo_v3/material_colors.xacro" />
  <xacro:include filename="$(find cugo_ros2_control)/models/cugo_v3/gazebo_material_macro.xacro" />

  <xacro:property name="body_width" value="0.42" />
  <xacro:property name="body_depth" value="0.58" />
  <xacro:property name="body_height" value="0.26" />

  <xacro:property name="tbox_width" value="0.42" />
  <xacro:property name="tbox_depth" value="0.58" />
  <xacro:property name="tbox_height" value="0.20" />

  <xacro:property name="body_collision_width" value="0.42" />
  <xacro:property name="body_collision_depth" value="0.58" />
  <xacro:property name="body_collision_height" value="0.20" />

  <xacro:property name="wheel_length" value="0.06" />
  <xacro:property name="collision_wheel_length" value="0.145" />
  <!-- 当たり判定の径 -->
  <xacro:property name="wheel_radius" value="0.03858" />
  <!-- スプロケット径 -->
  <xacro:property name="mini_wheel_radius" value="0.03858" />

  <xacro:property name="wheel_diameter" value="0.07716" />

  <xacro:property name="max_wheel_acceleration" value="1.0" />
  <xacro:property name="max_wheel_torque" value="5.0" />

  <xacro:property name="big_wheel_front_x" value="0.172" />
  <xacro:property name="big_wheel_back_x" value="-0.172" />
  <xacro:property name="center_wheel_z" value="-0.105" />
  <xacro:property name="big_wheel_z" value="-0.08" />

  <xacro:property name="left_wheel_y" value="0.24" />
  <xacro:property name="right_wheel_y" value="-0.22" />



  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.1065" rpy="0 0 0"/>
  </joint>

  <link name="base_link"/>

  <joint name="body_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="base_body"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_body">
    <visual>
      <geometry>
        <mesh filename="file://$(find cugo_ros2_control)/models/cugo_v3/meshes/roskit-Compound.dae" scale="1 1 1"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 -1.57"/>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.13542" iyy="0.10833" izz="0.17708" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="body_collision_joint" type="fixed">
    <parent link="base_body"/>
    <child link="body_collision"/>
    <origin xyz="0 0 ${body_collision_height/2+body_height/2-0.05}" rpy="0 0 0"/>
  </joint>

  <link name="body_collision">
    <visual>
      <geometry>
        <box size="${body_collision_width} ${body_collision_depth} ${body_collision_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_collision_width} ${body_collision_depth} ${body_collision_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.13542" iyy="0.10833" izz="0.17708" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="0.5" velocity="2.0"/>
    <parent link="base_body"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${left_wheel_y} ${center_wheel_z}" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${collision_wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint_center_mini_front" type="continuous">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1.0" velocity="2.0"/>
    <parent link="base_body"/>
    <child link="left_wheel_center_mini_front"/>
    <origin xyz="${mini_wheel_radius*2} ${left_wheel_y} ${center_wheel_z}" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="left_wheel_center_mini_front">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${collision_wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint_center_mini_back" type="continuous">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1.0" velocity="2.0"/>
    <parent link="base_body"/>
    <child link="left_wheel_center_mini_back"/>
    <origin xyz="-${mini_wheel_radius*2} ${left_wheel_y} ${center_wheel_z}" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="left_wheel_center_mini_back">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${collision_wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint_big_front" type="continuous">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1.0" velocity="2.0"/>
    <parent link="base_body"/>
    <child link="left_wheel_big_front"/>
    <origin xyz="${big_wheel_front_x} ${left_wheel_y} ${big_wheel_z}" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="left_wheel_big_front">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${collision_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint_big_back" type="continuous">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1.0" velocity="2.0"/>
    <parent link="base_body"/>
    <child link="left_wheel_big_back"/>
    <origin xyz="${big_wheel_back_x} ${left_wheel_y} ${big_wheel_z}" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="left_wheel_big_back">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${collision_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1.0" velocity="2.0"/>
    <parent link="base_body"/>
    <child link="right_wheel"/>
    <origin xyz="0 ${right_wheel_y} ${center_wheel_z}" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${collision_wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint_center_mini_front" type="continuous">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1.0" velocity="2.0"/>
    <parent link="base_body"/>
    <child link="right_wheel_center_mini_front"/>
    <origin xyz="${mini_wheel_radius*2} ${right_wheel_y} ${center_wheel_z}" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="right_wheel_center_mini_front">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${collision_wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint_center_mini_back" type="continuous">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1.0" velocity="2.0"/>
    <parent link="base_body"/>
    <child link="right_wheel_center_mini_back"/>
    <origin xyz="-${mini_wheel_radius*2} ${right_wheel_y} ${center_wheel_z}" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="right_wheel_center_mini_back">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${collision_wheel_length}" radius="${mini_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint_big_front" type="continuous">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1.0" velocity="2.0"/>
    <parent link="base_body"/>
    <child link="right_wheel_big_front"/>
    <origin xyz="${big_wheel_front_x} ${right_wheel_y} ${big_wheel_z}" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="right_wheel_big_front">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${collision_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint_big_back" type="continuous">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1.0" velocity="2.0"/>
    <parent link="base_body"/>
    <child link="right_wheel_big_back"/>
    <origin xyz="${big_wheel_back_x} ${right_wheel_y} ${big_wheel_z}" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="right_wheel_big_back">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <material name="dummy_white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${collision_wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="left_crawler_joint" type="fixed">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <parent link="base_body"/>
    <child link="left_crawler"/>
    <origin xyz="-0.01 0.22 -0.043" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="left_crawler">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find cugo_ros2_control)/models/cugo_v3/meshes/cugo_v3_l-CuGoV3_L001.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="right_crawler_joint" type="fixed">
    <axis xyz="0 0 -1" rpy="0 0 0"/>
    <parent link="base_body"/>
    <child link="right_crawler"/>
    <origin xyz="-0.10 -0.2065 -0.055" rpy="0 1.57075 -1.57"/>
  </joint>

  <link name="right_crawler">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find cugo_ros2_control)/models/cugo_v3/meshes/cugo_v3_r-CuGoV3_R001.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00024" iyy="0.00024" izz="0.00015" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <!--diff_drive_controller plugin-->
  <gazebo>
    <plugin name="cugo_diff_drive" filename="libgazebo_ros_diff_drive.so">
      <update_rate>10</update_rate>
      <!-- wheels -->
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <!-- kinematics -->
      <wheel_separation>0.460</wheel_separation>
      <wheel_diameter>${wheel_diameter}</wheel_diameter>
      <!-- limits -->
      <max_wheel_acceleration>${max_wheel_acceleration}</max_wheel_acceleration>
      <max_wheel_torque>${max_wheel_torque}</max_wheel_torque>
      <command_topic>cmd_vel</command_topic>
      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <!--<publish_wheel_joint_state>true</publish_wheel_joint_state>-->
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
      <!--<robot_base_frame>base_link</robot_base_frame>-->
      <odometry_source>1</odometry_source>
      <!--<legacy_mode>false</legacy_mode>-->
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="cugo_diff_drive_mini_front" filename="libgazebo_ros_diff_drive.so">
      <update_rate>10</update_rate>
      <!-- wheels -->
      <left_joint>left_wheel_joint_center_mini_front</left_joint>
      <right_joint>right_wheel_joint_center_mini_front</right_joint>
      <!-- kinematics -->
      <wheel_separation>0.460</wheel_separation>
      <wheel_diameter>${wheel_diameter}</wheel_diameter>
      <!-- limits -->
      <max_wheel_acceleration>${max_wheel_acceleration}</max_wheel_acceleration>
      <max_wheel_torque>${max_wheel_torque}</max_wheel_torque>
      <command_topic>cmd_vel</command_topic>
      <legacyMode>false</legacyMode>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="cugo_diff_drive_mini_back" filename="libgazebo_ros_diff_drive.so">
      <update_rate>10</update_rate>
      <!-- wheels -->
      <left_joint>left_wheel_joint_center_mini_back</left_joint>
      <right_joint>right_wheel_joint_center_mini_back</right_joint>
      <!-- kinematics -->
      <wheel_separation>0.460</wheel_separation>
      <wheel_diameter>${wheel_diameter}</wheel_diameter>
      <!-- limits -->
      <max_wheel_acceleration>${max_wheel_acceleration}</max_wheel_acceleration>
      <max_wheel_torque>${max_wheel_torque}</max_wheel_torque>
      <command_topic>cmd_vel</command_topic>
      <legacyMode>false</legacyMode>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="cugo_diff_drive_big_front" filename="libgazebo_ros_diff_drive.so">
      <update_rate>10</update_rate>
      <!-- wheels -->
      <left_joint>left_wheel_joint_big_front</left_joint>
      <right_joint>right_wheel_joint_big_front</right_joint>
      <!-- kinematics -->
      <wheel_separation>0.460</wheel_separation>
      <wheel_diameter>${wheel_diameter}</wheel_diameter>
      <!-- limits -->
      <max_wheel_acceleration>${max_wheel_acceleration}</max_wheel_acceleration>
      <max_wheel_torque>${max_wheel_torque}</max_wheel_torque>
      <command_topic>cmd_vel</command_topic>
      <legacyMode>false</legacyMode>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="cugo_diff_drive_big_back" filename="libgazebo_ros_diff_drive.so">
      <update_rate>10</update_rate>
      <!-- wheels -->
      <left_joint>left_wheel_joint_big_back</left_joint>
      <right_joint>right_wheel_joint_big_back</right_joint>
      <!-- kinematics -->
      <wheel_separation>0.460</wheel_separation>
      <wheel_diameter>${wheel_diameter}</wheel_diameter>
      <!-- limits -->
      <max_wheel_acceleration>${max_wheel_acceleration}</max_wheel_acceleration>
      <max_wheel_torque>${max_wheel_torque}</max_wheel_torque>
      <command_topic>cmd_vel</command_topic>
      <legacyMode>false</legacyMode>
    </plugin>
  </gazebo>

  <!-- gazebo上のパーツ設定 -->
  <xacro:gazebo_material ref="right_wheel" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="right_wheel_center_mini_front" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="right_wheel_center_mini_back" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="right_wheel_mini_front" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="right_wheel_mini_back" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="right_wheel_big_front" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="right_wheel_big_back" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>

  <xacro:gazebo_material ref="left_wheel" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="left_wheel_center_mini_front" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="left_wheel_center_mini_back" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="left_wheel_mini_front" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="left_wheel_mini_back" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="left_wheel_big_front" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>
  <xacro:gazebo_material ref="left_wheel_big_back" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>

  <xacro:gazebo_material ref="body_collision" mu="2.0">
    <material>Gazebo/GreyTransparent</material>
  </xacro:gazebo_material>

  <!-- 2D LiDAR -->
  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.0 0.0 0.04" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 -1.57"/>
      <geometry>
        <mesh filename="file://$(find cugo_ros2_control)/models/cugo_v3/meshes/lds.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>
    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

  <gazebo reference="base_scan">
    <material>Gazebo/Grey</material>
    <sensor type="ray" name="scan">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>30</update_rate>
      <always_on>true</always_on>
      <ray>
        <scan>
          <horizontal>
            <samples>400</samples>
            <resolution>1</resolution>
            <min_angle>${radians(-180)}</min_angle>
            <max_angle>${radians( 180)}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>20.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_lidar_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <topicName>/base_scan/scan</topicName>
        <frameName>base_scan</frameName>
      </plugin>
    </sensor>
  </gazebo>

</robot>
